
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navebar from "@/components/Navebar/Navebar";
import SideBar from "@/components/SideBar/SideBar";
import { GlobalProvider } from "@/contexts/GlobalContext";
import Overlay from "@/components/Overlay/Overlay";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <GlobalProvider>
          <Navebar />
          <SideBar /> 
          <Overlay />
          {children}
        </GlobalProvider>
      </body>
    </html>
  );
}
